version: 2
jobs:
  build:
    working_directory: .
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            pip install docker-compose
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            ls
            docker-compose run app sh -c "python manage.py test && flake8"